# Project Settings
APP = nengo-tx
SOURCES = test_tx.c
OBJECTS = $(SOURCES:.c=.o)
OBJECTS += ../common/bit_field.o ../common/spikes.o ../common/out_spikes.o ../common/configuration.o ../common/recording.o
CFLAGS += -I ../common/

include ../Makefile.depend
