# SpiNNaker Nengo Integration
# (SpiNNaker to Host) Transmitter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_tx
SOURCES = tx-harness.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
