# SpiNNaker Nengo Integration
# Dimension Source Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

NENGO_APP = nengo_rx
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = sdp-rx-main.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
