# SpiNNaker Nengo Integration
# Dimension Source Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_rx
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = sdp-rx-main.c ../common/disciplined_clock.c ../common/disciplined_timer.c ../common/discipline.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
