# SpiNNaker Nengo Integration
# Dimension Source Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_rx
SOURCES = rx-harness.c rx-data.c rx-sdp.c rx-update.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
