# SpiNNaker Nengo Integration
# Ensemble Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_ensemble
SOURCES = ensemble-harness.c ensemble-io.c ensemble-update.c ensemble-data.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
