# SpiNNaker Nengo Integration
# Ensemble Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_ensemble
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = ensemble-main.c ensemble-data.c ensemble-harness.c ../common/filtered-input.c ensemble-output.c ensemble-update.c recording.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
