APP = nengo_value_source
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = value_source.c ../common/disciplined_clock.c ../common/disciplined_timer.c ../common/discipline.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
