# SpiNNaker Nengo Integration
# Dimension Source Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_dimsource
SOURCES = dimension_source.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
