# SpiNNaker Nengo Integration
# Simulation Controller
# ----------------------------------------------------------------------------
# Authors:
#  Jonathan Heathcote <jdh@cs.man.ac.uk>
# ----------------------------------------------------------------------------

APP = sim_controller
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = sim_controller.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
