# SpiNNaker Nengo Integration
# Filter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# April 2014
# ----------------------------------------------------------------------------

APP = nengo_filter
SOURCES = filter-main.c ../common/filtered-input.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
