# SpiNNaker Nengo Integration
# Filter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# April 2014
# ----------------------------------------------------------------------------

APP = nengo_filter
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = filter_main.c ../common/input_filter.c ../common/disciplined_clock.c ../common/disciplined_timer.c ../common/discipline.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
