APP = nengo_value_sink
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = value_sink.c ../common/input_filter.c ../common/disciplined_clock.c ../common/disciplined_timer.c ../common/discipline.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
