# SpiNNaker Nengo Integration
# (SpiNNaker to Host) Transmitter Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_tx
APP_OUTPUT_DIR = $(PWD)/../../nengo_spinnaker/binaries/
SOURCES = sdp_tx_main.c ../common/input_filter.c
OBJECTS = $(SOURCES:.c=.o)
include ../Makefile.depend
